In [12]:
import numpy as np

In [13]:
import IrisDataLoader as iLoader

In [7]:
RawData, RawLabels = iLoader.DataWithBias_Labels(1)

In [8]:
DataRowCnt, DataColCnt = RawData.shape

In [9]:
for i in range(DataRowCnt):
    if RawLabels[i] == 1:
        RawLabels[i] = 0
    else:
        RawLabels[i] = 1

In [19]:
def Sigmoid_Func(inData):
    return 1 / (1 + np.exp(-inData))

In [20]:
Sigmoid_Func(RawData[:, 1])

array([ 0.9939402 ,  0.99260846,  0.9909867 ,  0.9900482 ,  0.99330715,
        0.99550373,  0.9900482 ,  0.99330715,  0.98787157,  0.99260846,
        0.99550373,  0.99183743,  0.99183743,  0.98661308,  0.99698158,
        0.99666519,  0.99550373,  0.9939402 ,  0.99666519,  0.9939402 ,
        0.99550373,  0.9939402 ,  0.9900482 ,  0.9939402 ,  0.99183743,
        0.99330715,  0.99330715,  0.9945137 ,  0.9945137 ,  0.9909867 ,
        0.99183743,  0.99550373,  0.9945137 ,  0.99592986,  0.99260846,
        0.99330715,  0.99592986,  0.99260846,  0.98787157,  0.9939402 ,
        0.99330715,  0.98901306,  0.98787157,  0.99330715,  0.9939402 ,
        0.99183743,  0.9939402 ,  0.9900482 ,  0.9950332 ,  0.99330715,
        0.99908895,  0.9983412 ,  0.99899323,  0.99592986,  0.99849882,
        0.99666519,  0.99816706,  0.99260846,  0.99864148,  0.9945137 ,
        0.99330715,  0.99726804,  0.99752738,  0.99776215,  0.99631576,
        0.9987706 ,  0.99631576,  0.99698158,  0.99797468,  0.99

In [17]:
RawLabels

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
      

In [18]:
RawData

array([[ 1. ,  5.1,  3.5,  1.4,  0.2],
       [ 1. ,  4.9,  3. ,  1.4,  0.2],
       [ 1. ,  4.7,  3.2,  1.3,  0.2],
       [ 1. ,  4.6,  3.1,  1.5,  0.2],
       [ 1. ,  5. ,  3.6,  1.4,  0.2],
       [ 1. ,  5.4,  3.9,  1.7,  0.4],
       [ 1. ,  4.6,  3.4,  1.4,  0.3],
       [ 1. ,  5. ,  3.4,  1.5,  0.2],
       [ 1. ,  4.4,  2.9,  1.4,  0.2],
       [ 1. ,  4.9,  3.1,  1.5,  0.1],
       [ 1. ,  5.4,  3.7,  1.5,  0.2],
       [ 1. ,  4.8,  3.4,  1.6,  0.2],
       [ 1. ,  4.8,  3. ,  1.4,  0.1],
       [ 1. ,  4.3,  3. ,  1.1,  0.1],
       [ 1. ,  5.8,  4. ,  1.2,  0.2],
       [ 1. ,  5.7,  4.4,  1.5,  0.4],
       [ 1. ,  5.4,  3.9,  1.3,  0.4],
       [ 1. ,  5.1,  3.5,  1.4,  0.3],
       [ 1. ,  5.7,  3.8,  1.7,  0.3],
       [ 1. ,  5.1,  3.8,  1.5,  0.3],
       [ 1. ,  5.4,  3.4,  1.7,  0.2],
       [ 1. ,  5.1,  3.7,  1.5,  0.4],
       [ 1. ,  4.6,  3.6,  1. ,  0.2],
       [ 1. ,  5.1,  3.3,  1.7,  0.5],
       [ 1. ,  4.8,  3.4,  1.9,  0.2],
       [ 1. ,  5. ,  3. ,